In [0]:
import torch
import numpy

In [0]:
x = torch.tensor([4, 3])
x

tensor([4, 3])

In [0]:
print(x.size())

torch.Size([2])


In [0]:
y = torch.tensor([30, 40])
print(x +y)

tensor([34, 43])


In [0]:
z = torch.randn(5, 4)

In [0]:
y = z.view(20, 1)
print(y)

tensor([[ 0.7312],
        [ 0.9155],
        [ 0.0081],
        [ 0.7661],
        [-0.9993],
        [ 1.8337],
        [-0.3602],
        [ 0.3013],
        [ 1.3164],
        [ 0.5175],
        [ 0.7750],
        [ 0.0337],
        [-0.2215],
        [-0.4511],
        [ 0.7323],
        [ 0.3111],
        [ 0.7098],
        [ 1.4554],
        [ 0.3160],
        [-0.3463]])


In [0]:
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [0]:
d = y.numpy()
d

array([[ 0.7311953 ],
       [ 0.91548413],
       [ 0.00805746],
       [ 0.7661167 ],
       [-0.99930793],
       [ 1.8337154 ],
       [-0.3602485 ],
       [ 0.30125996],
       [ 1.3163524 ],
       [ 0.5174871 ],
       [ 0.7749841 ],
       [ 0.03367734],
       [-0.22146755],
       [-0.4511178 ],
       [ 0.73233366],
       [ 0.31109568],
       [ 0.7097798 ],
       [ 1.4553906 ],
       [ 0.31598857],
       [-0.34632686]], dtype=float32)

In [0]:
q = torch.from_numpy(d)
print(q)

tensor([[ 0.7312],
        [ 0.9155],
        [ 0.0081],
        [ 0.7661],
        [-0.9993],
        [ 1.8337],
        [-0.3602],
        [ 0.3013],
        [ 1.3164],
        [ 0.5175],
        [ 0.7750],
        [ 0.0337],
        [-0.2215],
        [-0.4511],
        [ 0.7323],
        [ 0.3111],
        [ 0.7098],
        [ 1.4554],
        [ 0.3160],
        [-0.3463]])


In [0]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones(4, 5, device = device)