In [0]:
import numpy as np

In [2]:
a = np.array([1, 2, 4])
a

array([1, 2, 4])

In [3]:
b = np.array([[[1, 2, 3], [4, 2, 8]], [[5, 6, 7], [9, 4, 20]]])
b

array([[[ 1,  2,  3],
        [ 4,  2,  8]],

       [[ 5,  6,  7],
        [ 9,  4, 20]]])

In [4]:
b.ndim

3

In [5]:
b.shape

(2, 2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [8]:
a.nbytes

24

In [9]:
b[0, 1, 2]

8

In [10]:
b[:, 1, :2]

array([[4, 2],
       [9, 4]])

In [11]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4, 5, 2), dtype = 'int16')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [13]:
np.full((2, 4), 89)

array([[89, 89, 89, 89],
       [89, 89, 89, 89]])

In [14]:
np.full_like(b, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [15]:
np.random.rand(3,2,5)

array([[[0.56869735, 0.91827093, 0.20010406, 0.41242155, 0.2854651 ],
        [0.52524998, 0.73606112, 0.81151131, 0.93810476, 0.82787132]],

       [[0.28526986, 0.06723177, 0.99790425, 0.92794692, 0.62322034],
        [0.75483619, 0.0142675 , 0.08490744, 0.42199087, 0.3376798 ]],

       [[0.98877573, 0.8163842 , 0.97154004, 0.22440749, 0.13621254],
        [0.7928243 , 0.33046527, 0.85703139, 0.8134035 , 0.55267554]]])

In [16]:
np.random.randint(4, size = (3, 6))

array([[1, 1, 0, 3, 3, 3],
       [1, 0, 1, 2, 3, 1],
       [1, 3, 3, 2, 2, 3]])

In [17]:
np.random.random_sample(b.shape)

array([[[0.23373476, 0.44617948, 0.95354954],
        [0.25492801, 0.08545482, 0.33706411]],

       [[0.00763894, 0.60914498, 0.33479045],
        [0.51015893, 0.88218454, 0.11523233]]])

In [18]:
a = np.ones([4, 5])
b = a

b[1, 4] = 0

a


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
c = a.copy()

c[1,2] = 0

a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
a = np.array([3, 5, 3, 2])

a += 2

a


array([5, 7, 5, 4])

In [21]:
a * 5


array([25, 35, 25, 20])

In [0]:
a -= 4

In [23]:
np.cos(a)



array([ 0.54030231, -0.9899925 ,  0.54030231,  1.        ])

In [24]:
np.matmul(a, b)

array([5., 5., 5., 5., 2.])

In [25]:
np.sum(a)

5

In [26]:
np.max(a, axis =0)

3

In [27]:
before = np.zeros([2, 3])

after = before.reshape(6,1)

print(after)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [28]:
a > 0

array([ True,  True,  True, False])